events {}

http {
  upstream product_service_backend {
    server product-service:3000;
  }

  upstream category_service_backend {
    server category-service:8085;
  }

  server {
    listen 80;

    location /productos/ {
      proxy_pass http://product_service_backend/api/products/;
    }

    location /categorias/ {
      proxy_pass http://category_service_backend/api/categories/;
    }
  }
}