server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: thisisaverylongsecretkeystringthatneedstobeatleast64byteslong!!!
