events {}

http {
  # Rutas para product-service
  upstream product-service {
    server product-service:3000;
  }

  # Rutas para category-service
  upstream category-service {
    server category-service:3002;
  }

  # Rutas para auth-service
  upstream auth-service {
    server host.docker.internal:8080;
  }

  **# Rutas para user-profile-service
  upstream user-profile-service {
    server host.docker.internal:8081;
  }**

  server {
    listen 80;

    # Ruta para productos
    location /productos/ {
      proxy_pass http://product-service/api/products/;
      proxy_set_header Host $host;
    }

    # Ruta para categorías
    location /categorias/ {
      proxy_pass http://category-service/api/categories/;
      proxy_set_header Host $host;
    }

    # Documentación Swagger para categoría
    location /categorias-docs/ {
      proxy_pass http://category-service/api-docs/;
      proxy_set_header Host $host;
    }

    # Rutas para autenticación (auth-service)
    location /auth/ {
      proxy_pass http://auth-service/;
      proxy_set_header Host $host;
    }

    **# Ruta para perfiles de usuario
    location /perfiles/ {
      proxy_pass http://user-profile-service/profiles/;
      proxy_set_header Host $host;
    }**
  }
}
