
server:
  port: 8089

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
        - id: user-profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/**
        - id: rbac-service
          uri: http://localhost:8082
          predicates:
            - Path=/rbac/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /api/products/${segment}  
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payment/**
        - id: category-service
          uri: http://localhost:8085
          predicates:
            - Path=/category/**
        - id: inventory-service
          uri: http://localhost:8088
          predicates:
            - Path=/inventory/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
