spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: thisisaverylongsecretkeystringthatneedstobeatleast64byteslong!!!
