version: '3.8'

services:
  category-service:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - MONGO_URI=mongodb://mongo:27017/ecuador-ceramico
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ecuador-ceramico
    restart: unless-stopped

volumes:
  mongo-data:
